// <auto-generated />
using BlueberryMuffin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueberryMuffin.Migrations
{
    [DbContext(typeof(BlueberryDbContext))]
    [Migration("20240922104720_SeededContriesAndHotels")]
    partial class SeededContriesAndHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlueberryMuffin.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeName = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 2,
                            CodeName = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 3,
                            CodeName = "UA",
                            Name = "Ukraine"
                        });
                });

            modelBuilder.Entity("BlueberryMuffin.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kingston",
                            CountryId = 1,
                            Name = "Courtleigh Hotel & Suites The",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "New York",
                            CountryId = 2,
                            Name = "Hyatt Place New York City",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Lviv",
                            CountryId = 3,
                            Name = "ibis Lviv Center",
                            Rating = 3.1000000000000001
                        });
                });

            modelBuilder.Entity("BlueberryMuffin.Models.Hotel", b =>
                {
                    b.HasOne("BlueberryMuffin.Models.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BlueberryMuffin.Models.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
